apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: url-shortener
  type: NodePort
  ports:
   -  protocol: TCP
      port: 8090
      targetPort: {{ .Values.serverPort }}

