#!/usr/bin/env bash
#
# git config core.hooksPath .githooks
#
set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# exec "${REPO_ROOT}/hack/verify-kep-metadata.sh"

