---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
 
# Remove SA to use ImagePullSecret from default SA
# See minikube registry creds feature (https://minikube.sigs.k8s.io/docs/handbook/registry/)
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/serviceAccountName
