---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echoserver
  name: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echoserver
      annotations:
        k9scli.io/auto-port-forwards: echoserver::3330:3335
    spec: 
      imagePullSecrets: []
      containers:
      - name: echoserver
        image: ghcr.io/liam-murray-xealth/echoserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3335
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5001
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
            #cpu: 1000m
        env:
        - name: PORT
          value: "3335"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config

      volumes:
      - name: config-volume
        configMap:
          name: echoserver-config


