apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: echoserver
resources:
  - deployment.yaml
  - service.yaml

# Example config (not used)
configMapGenerator:
  - name: echoserver-config
    files:
      - ./files/config.yaml
generatorOptions:
  labels:
    type: generated


