---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  selector:
    app: echoserver
  # externalTrafficPolicy: Local
  ports:
   -  protocol: TCP
      port: 5000
      targetPort: 3335



